import os


# APP SETTINGS
APP_NAME = "PyVault"
APP_VERSION = "0.2.0"

EXCLUDED_FILES = ["config.json"]


# CONSTANTS
ENCRYPT_CHUNK_SIZE = 524288
DECRYPT_CHUNK_SIZE = 699148

FILENAME_ENCRYPT_CHUNK_SIZE = 256
FILENAME_DECRYPT_CHUNK_SIZE = 440

EMPTY_CHAR = "░"
FILL_CHAR = "█"
MAX_FILE_CHAR_LEN = 30

CHECKBOX_TICK_CHAR = "●"
CHECKBOX_TICK_STYLE = "#429ef5"
CHECKBOX_CURSOR_STYLE = "#429ef5"